export type Maintenance = {
    id: number,
    codOS: number,
    dataOS: string,
    dataAprovacaoOS: string | null,
    dataFinalizacaoOS: string | null,
    dataEntregaVeiculo: string | null,
    dataOrcamentoOS: string | null,
    dataRejeitaOS: string | null,
    dataCancelamentoOS: string | null,
    marca: string,
    modelo: string,
    placa: string,
    prefixo: string | null,
    cidade: string,
    base: string,
    subunidade: string,
    status: string,
    posto: string,
    optanteSimplesNacional: string,
    valorPecas: number,
    valorMaoDeObra: number,
    valorTotal: number,
    situacaoOS: string | null,
    statusSituacaoOS: string | null,
}