export type Supply = {
    id: number,
    cod_transaction: string | null,
    transaction_date: string | null,
    license_plate: string | null,
    car_model: string | null,
    year: string | null,
    matricula: string | null,
    driver_name: string | null,
    fuel_type: string | null,
    liters: number | null,
    value_liter: number | null,
    hodometro: number | null,
    kms_or_hours: number | null,
    km_per_liter: number | null,
    emission_value: number | null,
    cod_estabelecimento: string | null,
    nome_estabelecimento: string | null,
    endereco: string | null,
    bairro: string | null,
    cidade: string | null,
    UF: string | null,
    forma_transacao: string | null,
    serie_pos: string | null,
    numero_cartao: string | null,
    familia_veiculo: string | null
}