export enum EVehicleStatus {
    AVAILABLE = "AVAILABLE",
    TRAVEL = "TRAVEL",
    MAINTENANCE = "MAINTENANCE",
    REVISION = "REVISION",
    INACTIVE = "INACTIVE",
    DISCONTINUED = "DISCONTINUED"
}